version: "3.8"

services:
  ### From docker-compose-candidate.yml
  cdm-db:
    image: "inganalytics/cdm-db-medium:latest"
    container_name: cdm-db
    ports:
      - "5432:5432"
    networks:
      - "cdm" 
    platform: "linux/amd64"     

  cdm-api:
    image: "inganalytics/cdm-api:latest"
    container_name: cdm-api
    environment:
      - SIZE_SETTING=medium
    ports:
      - "8080:8080"
    networks:
      - "cdm"        
    restart: "on-failure"
    depends_on:
      - cdm-db
    platform: "linux/amd64"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      - SWAGGER_JSON_URL=http://localhost:8080/apidocs.json
    ports:
      - "80:8080"
    networks:
      - "cdm"            
    depends_on:  
      - cdm-api
    platform: "linux/amd64"
  ### End 

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - "cdm" 

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    networks:
      - "cdm" 

  worker:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
    networks:
      - "cdm" 

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    depends_on:
      - worker
      - redis
    command: celery --broker=redis://redis:6379/0 --result-backend=redis://redis:6379/0 flower
    networks:
      - "cdm" 

networks:
  cdm:
    name: "cdm"
