# Dockerfile

FROM python:3.9-slim

WORKDIR /app

ADD . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN groupadd -r celerygroup && useradd -r -g celerygroup celeryuser

RUN chown -R celeryuser:celerygroup /app

USER celeryuser

CMD ["celery", "-A", "tasks", "worker", "--beat", "--loglevel=info"]



